filter:
  excluded_paths:
    - bin/*
    - gui/*
    - languages/*
    - tests/*
    - src/includes/admin/views/*

checks:
  php:
    code_rating: true
    coding_standard: WordPress

tools:
    external_code_coverage: false

    php_sim:
        enabled: true
        min_mass: 50

    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php

    php_analyzer:
        enabled: true
        extensions:
            - php

    php_hhvm:
        enabled: true
        command: hhvm
        extensions:
            - php
